### ISSUE TITLE
INVALID_CARD_DATA issue

### ISSUE THREAD

**Issue by wviveiro** [square/connect-php-sdk#61] opened 2018-07-11 00:24 UTC
I have been receiving this error when trying to create a credit card on file. Not for all clients thought, just some specifics credit cards....

Does anyone know what the problem could be? Cardholder name maybe?

Tried to find on google as well, but couldn't find an answer.

Thanks!

**Comment by StephenJosey** [comment] 2018-07-11 21:19
@wviveiro are you receiving an error message with it? The `INVALID_CARD_DATA` is the error code, but the message could potentially have more information as to why it's being triggered.

**Comment by StephenJosey** [comment] 2018-07-12 17:44
@wviveiro please email developers@help-messaging.squareup.com with a bit more detail (like your Square associated email), so that we check our logs to see what the root cause of this error is. Thank you!

**Comment by wviveiro** [comment] 2018-07-13 02:02
@StephenJosey. My team has sent and e-mail to square already, they said they are looking into it, but it's been 3 weeks already.... So I thought that I might find a solution here from people that had the same problem....

But thanks anyways!

**Comment by StephenJosey** [comment] 2018-07-31 15:42
@wviveiro just checking back in - were you able to resolve this issue? I believe I saw the case being handled by our customer success team, but just wanted to make sure. I'll close this for now, but if it's not resolved, definitely respond here and I'll make sure we figure it out. Thanks!

**Closed by StephenJosey** 2018-07-31 15:42 UTC

**Comment by wviveiro** [comment] 2018-08-01 00:30
Hi @StephenJosey ,

Square went back saying that it is a problem with the customer's bank, and sometimes the errors from the bank are not clear enough....

However the error that is coming back from the API is "Invalid Card Data". The main problem with this error message is that the users from my system believes the error is coming from my form... That would be good if the error was more specific, such error "invalid return from bank issuer", "transaction not authorised" or something like that.

Interesting enough, if I use the same credit card for a one off payment it works fine, it only fails when trying to save credit card on file.... 

Anyways, my team understand the problem is not from the system now. So case solved I guess

Thank you very much for the follow up @StephenJosey !
